### ISSUE TITLE
Installation fails due to cdtime dependency

### ISSUE THREAD

**Issue by chengzhuzhang** [ARM-DOE/arm-gcm-diagnostics#7]
This is related to following issue
https://github.com/CDAT/cdms/issues/300
cdat teams is looking into it. 

The recommended temporary fix is:
git clone git://github.com/cdat/cdtime
cd cdtime
python setup.py install

**Comment by chengzhuzhang** [comment]
This issue occur because when installing an old version of cdtime (2.10) through conda, some dependencies of it are the latest (i.e.,netcdf), causing above error.

Now there is an separate issue after updating to cdutil(3.1.0)
https://github.com/CDAT/cdat/issues/2224

**Comment by chengzhuzhang** [comment]
Installation update suggested by @doutriaux1 
```
conda create -n arm_diags_env_try4 cdp=1.0.3 cdutil cdms2 libcdms matplotlib scipy -c conda-forge -c uvcdat
```

**Comment by chengzhuzhang** [comment]
> This issue occur because when installing an old version of cdtime (2.10) through conda, some dependencies of it are the latest (i.e.,netcdf), causing above error.
> 
> Now there is an separate issue after updating to cdutil(3.1.0)
> [CDAT/cdat#2224](https://github.com/CDAT/cdat/issues/2224)

This issue is fixed in acc64d9

**Comment by doutriaux1** [comment]
@chengzhuzhang please let me know if we can further help you or if anything similar happens again in the future.

**Comment by chengzhuzhang** [comment]
Thank you, Charles! @doutriaux1
